### ISSUE TITLE
Exception in Serializer when not a local pid

### ISSUE THREAD

**Issue by alanvardy** [MikaAK/elixir_error_message#8]
![image](https://github.com/MikaAK/elixir_error_message/assets/38899847/7230fe9c-1daa-4615-abd7-292890b880ae)

What do you think of me putting a rescue in there for this case?

**Comment by MikaAK** [comment]
Fixable! We can scan for pids and remove them as well 😄

**Comment by MikaAK** [comment]
Fixed in 0.3.1
